# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
name: Docker-CI
trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

resources:
  - repo: self

variables:
  tag: "ui.$(Build.BuildId)"
  repositoryName: "luifa7/recommendoo"

stages:
  - stage: BuildAndPush
    displayName: Build and push image
    jobs:
      - job: DockerImage
        displayName: Build and push Docker Image
        steps:
          - task: Docker@2
            displayName: Build the Docker image
            inputs:
              containerRegistry: dockerHub
              repository: "$(repositoryName)"
              command: build
              dockerfile: "$(Build.SourcesDirectory)/Dockerfile"
              tags: "$(tag)"
              includeLatestTag: true
              useDefaultContext: false
              buildContext: "."
          - task: Docker@2
            displayName: Push the Docker image to DockerHub
            inputs:
              containerRegistry: dockerHub
              repository: "$(repositoryName)"
              command: push
              tags: "$(tag)"
            condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
